name = "glitterhub"
main = "./dist/client/_worker.js"
compatibility_date = "2022-05-04"
workers_dev = true
compatibility_flags = ["streams_enable_constructors"]

[build]
command = "pnpm build cloudflare-workers"

[site]
    bucket = "./dist/client"

[vars]
VITE_GITHUB_TOKEN="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"