name = "glitterhub-github-oauth"
main = "./dist/worker.js"
compatibility_date = "2022-05-04"
account_id = ""
workers_dev = true
type = "javascript"


[build]
command = "pnpm build cloudflare-workers"

[vars]
CLIENT_ID = "XX"
CLIENT_SECRET = ""